set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g prefix C-t
set -g mouse on
set -g status off
set -s escape-time 0
set-option -g focus-events on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind-key w new-window -c "#{pane_current_path}"
bind-key h split-window -h -c "#{pane_current_path}"
bind-key v split-window -v -c "#{pane_current_path}"
bind-key t choose-tree
bind-key x kill-pane 
bind-key k kill-window 
bind-key f run-shell '[[ "$(tmux display-message -p -F "#{session_name}")" = "floating" ]] && tmux detach-client || tmux display-popup -E -h 90% -w 90% "tmux new-session -A -s floating"'

bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
unbind-key -T copy-mode C-n
if-shell "uname | grep -q Darwin" "set-option -g status-position top; set -Fg 'status-format[1]' ''; set -g 'status-format[0]' ''; set -g status 2; set-option -g status-style bg=default

