env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

monitor = $PRIMARY_MONITOR,2560x1440@165,0x0,1
monitor = $SECONDARY_MONITOR,1920x1080@75,2560x0,1

exec-once = $BIN/start

misc {
   vrr = 2
}

input {
    sensitivity = -0.8
    follow_mouse = 2
	numlock_by_default = true
}

general {
    gaps_in = 5
    gaps_out = 10
	col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
	resize_on_border = true
	border_size = 0
}

decoration {
    rounding = 0

    blur {
        size = 3
        passes = 3
		popups = true
    }
}

animations {
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 3, myBezier
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    
    bezier=overshot,0.05,0.9,0.1,1.1
    bezier=overshot,0.13,0.99,0.29,1.1
    animation = windowsMove, 1, 5, myBezier
    animation = windowsOut, 1, 5, myBezier 
    animation = fade, 1, 5, default
}

binds {
    workspace_center_on = 1
}

windowrulev2 = noborder,focus:0
windowrulev2 = float,class:^(ApplicationLauncher)$
windowrulev2 = float,class:^(DropdownTerminal)$
windowrulev2 = workspace 3 silent,class:^(steam_app)(.*)$
windowrulev2 = workspace 4 silent,class:^(steam_proton)(.*)$
windowrulev2 = workspace 4 silent,class:^com.usebottles.bottles$

windowrulev2 = opacity 0.85,class:.*
windowrulev2 = opacity 1.0,fullscreen:1
windowrulev2 = opacity 1.0,title:^(Alacritty)$
windowrulev2 = opacity 1.0,title:^(Picture)(.*)$
windowrulev2 = opacity 1.0,class:^(steam_app)(.*)$

windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = maxsize 500 600,class:^(pavucontrol)$
windowrulev2 = move cursor -75% -103%,class:^(pavucontrol)$

$Meh = ALT SHIFT CONTROL
$Hyper = ALT SHIFT CONTROL SUPER

bind = $Meh,T,exec,alacritty
bind = $Meh,B,exec,firefox
bind = $Hyper,Z,exec,brave --password-store=basic
bind = $Meh,D,exec,$BIN/dropdown
bind = $Meh,F,fullscreen,1
bind = $Meh,G,togglefloating,
bind = $Meh,C,killactive,
bind = $Meh,P,exec,grim -g "$(slurp -d)" - | wl-copy
bind = $Meh,W,exec,$BIN/wallpaper
bind = SUPER,Space,exec,$BIN/run_launcher
bind = SUPER,L,exec,swaylock -c 000000

bind = $Hyper,N,exec,$BIN/movefocus l
bind = $Hyper,E,exec,$BIN/movefocus d
bind = $Hyper,I,exec,$BIN/movefocus u
bind = $Hyper,O,exec,$BIN/movefocus r

bind = $Meh,N,movewindow,l
bind = $Meh,E,movewindow,d
bind = $Meh,I,movewindow,u
bind = $Meh,O,movewindow,r
bindm = ,mouse:276,movewindow

bind = $Meh,M,workspace,r-1
bind = $Meh,code:61,workspace,r+1
bind = $Meh,code:59,movetoworkspace,r-1
bind = $Meh,code:60,movetoworkspace,r+1

binde = $Hyper,Q,resizeactive,-50 0
binde = $Hyper,W,resizeactive,0 50
binde = $Hyper,F,resizeactive,0 -50
binde = $Hyper,P,resizeactive,50 0
bindm = ,mouse:275,resizewindow 

bindle = ,XF86AudioRaiseVolume,exec,volumectl -u up
bindle = ,XF86AudioLowerVolume,exec,volumectl -u down
bindle = ,XF86AudioMute,exec,volumectl toggle-mute
bindl = $Hyper,M,exec,volumectl -m toggle-mute

bindl = ,XF86AudioPlay,exec,playerctl play-pause
bindl = ,XF86AudioNext,exec,playerctl next
bindl = ,XF86AudioPrev,exec,playerctl previous

