env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM="wayland;xcb"

exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/kdeconnectd
exec-once = hyprpaper & waybar & dunst & /bin/zsh -i -c "wifi"
exec-once = mullvad-vpn & kdeconnect-indicator
exec-once = $HOME/.local/bin/launcher "^Signal$"
monitor = DP-3,2560x1440@165,0x0,1,vrr,2
monitor = HDMI-A-1,1920x1080@75,-1080x0,1,transform,3

$terminal = alacritty
$menu = $HOME/.local/bin/run_launcher
$dropdown = $HOME/.local/bin/dropdown
$browser = $HOME/.local/bin/launcher "^Brave: Brave$"
$lock = $HOME/.config/hypr/lockscreen

input {
    sensitivity = -0.8
    follow_mouse = 2
}

general {
    gaps_out = 10
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    layout = master
    allow_tearing = false
}

decoration {
    rounding = 10

    Blur {
        size = 3
        passes = 3
        xray = true
    }
    
}

animations {
}

master {
    new_is_master = false
}

windowrulev2 = float,title:(AlacrittyLauncher)
windowrulev2 = float,title:(AlacrittyDropdown)
windowrulev2 = float,class:(.*exe$)
windowrulev2 = center,1,class:(Dunst)

$mainMod = ALT SHIFT CONTROL

bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, D, exec, $dropdown
bind = SUPER, Space, exec, $menu
bind = $mainMod, F, togglefloating,
bind = $mainMod, C, killactive,
bind = $mainMod, Q, exit,
bind = $mainMod, O, workspace, e+1
bind = $mainMod, N, workspace, e-1
bind = $mainMod, P, exec, grim -g "$(slurp -d)" - | wl-copy
bind = SUPER, L, exec, $lock

bindm = , mouse:276, movewindow
bindm = , mouse:275, resizewindow 

bind = ALT, Tab, cyclenext, bind = ALT, Tab, bringactivetotop,

bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindle = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous

