env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM="wayland;xcb"

monitor = DP-3,2560x1440@165,0x0,1,vrr,2
monitor = HDMI-A-1,1920x1080@75,-1080x0,1,transform,3

# exec-once = ~/.config/hypr/xdg-portal-hyprland
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/kdeconnectd
exec-once = hyprpaper & waybar & dunst & /bin/zsh -i -c "wifi"
exec-once = mullvad-vpn & kdeconnect-indicator
exec-once = signal-desktop --start-in-tray --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland

$terminal = alacritty
$menu = $HOME/.local/bin/run_launcher
$dropdown = $HOME/.local/bin/dropdown
$browser = $HOME/.local/bin/launcher "^Brave: Brave$"
$lock = $HOME/.config/hypr/lockscreen
$show_volume = $HOME/.local/bin/volume

input {
    sensitivity = -0.8
    follow_mouse = 2
}

general {
    gaps_out = 10
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    layout = master
}

decoration {
    rounding = 0

    Blur {
        size = 3
        passes = 3
    }
}

master {
    new_is_master = false
}

binds {
    workspace_center_on = 1
}

windowrulev2 = float,title:(AlacrittyLauncher)
windowrulev2 = float,title:(AlacrittyDropdown)
windowrulev2 = float,class:(.*exe$)

workspace = 1,persistent:true,monitor:DP-3
workspace = 2,persistent:true,monitor:DP-3
workspace = 3,persistent:true,monitor:DP-3
workspace = 4,persistent:true,monitor:DP-3
workspace = 5,persistent:true,monitor:HDMI-A-1

$mainMod = ALT SHIFT CONTROL

bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, D, exec, $dropdown
bind = SUPER, Space, exec, $menu
bind = $mainMod, F, togglefloating,
bind = $mainMod, C, killactive,
bind = $mainMod, Q, exit,
bind = $mainMod, O, workspace, e+1
bind = $mainMod, N, workspace, e-1
bind = $mainMod, P, exec, grim -g "$(slurp -d)" - | wl-copy
bind = ALT, Tab, cyclenext, bind = ALT, Tab, bringactivetotop,
bind = SUPER, L, exec, $lock

bindm = , mouse:276, movewindow
bindm = , mouse:275, resizewindow 

bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ & $show_volume
bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- & $show_volume
bindle = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle & $show_volume
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous

