preload = /home/eren/ssd/wallpapers/Adobe/AdobeStock_321371819.jpeg

wallpaper = DP-3,/home/eren/ssd/wallpapers/Adobe/AdobeStock_321371819.jpeg
wallpaper = HDMI-A-1,/home/eren/ssd/wallpapers/Adobe/AdobeStock_321371819.jpeg

splash = false

ipc = off

