preload = /home/eren/ssd/wallpapers/Adobe/AdobeStock_321371570.jpeg

wallpaper = DP-3,/home/eren/ssd/wallpapers/Adobe/AdobeStock_321371570.jpeg
wallpaper = HDMI-A-1,/home/eren/ssd/wallpapers/Adobe/AdobeStock_321371570.jpeg

splash = false

ipc = off

