add_newline = false

format = """
 $directory\
$git_branch\
$git_status\
$git_state\
$git_metrics
$character
"""

right_format = """
$cmd_duration\
$status
$time"""

[os]
disabled = false

[os.symbols]
Arch = "  "
Macos = "  "

[git_status]
ahead = "⇡$count "
behind = "⇣$count "
deleted = "-$count "
diverged = "⇡$ahead_count⇣$behind_count "
modified = "!$count "
staged = "+$count "
renamed = "-$count "
untracked = "?$count "
stashed = '📦$count '
format = '$all_status$ahead_behind'

[git_metrics]
disabled = false

[directory]
truncate_to_repo = false

[character]
success_symbol = '[ \$](bold green)'
error_symbol = '[ \$](bold red)'

[time]
disabled = false

