import = ["/home/eren/.config/alacritty/base16-windows-95.toml"]

[font]
size = 14.0

[font.normal]
family = "MesloLGS NF"

[shell]
program = "tmux"

[window]
opacity = 0.8
dynamic_padding = true
blur = true
decorations = "none"

[window.padding]
x = 5
y = 5

