import = ["/home/eren/.config/alacritty/base16-windows-95.toml"]

[font]
size = 13.0

[font.normal]
family = "MesloLGS NF"

[shell]
args = ["-c", "tmux attach -t Dropdown || tmux new -s Dropdown"]
program = "/bin/zsh"

[window]
decorations = "None"
opacity = 0.8

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 100
lines = 25

