[colors]
background = #00000000
foreground = #FFF
disabled = #707880

[bar/bar]
height = 28pt

width = 30%
# offset-x = 35%
offset-x = 10pt
offset-y = 7pt

bottom = true

dpi = 0

background = ${colors.background}
foreground = ${colors.foreground}

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "MesloLGS NF:size=12;0"

# modules-left = memory cpu cpu-temperature cpu-temperature-2 gpu-util gpu-temp gpu-power network 
modules-left = network 

[module/date]
type = internal/date
interval = 1

date = %d %b | %H:%M

label = %date%
label-foreground = ${colors.primary}

[module/memory]
type = internal/memory
format-prefix = "󰍛 "
label = %percentage_used%%

[module/cpu]
type = internal/cpu
format-prefix = "󰻠 "
label = %percentage%%

[module/network]
type = internal/network
interface-type = wireless
label-connected = 󰖩 %downspeed%

[module/cpu-temperature]
type = internal/temperature
thermal-zone = 1
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
label =  %temperature-c%

[module/cpu-temperature-2]
type = internal/temperature
thermal-zone = 1
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp1_input
label =  %temperature-c%

[module/gpu-util]
type = custom/script
exec = /bin/bash -c "echo  $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)%"

[module/gpu-temp]
type = custom/script
exec = /bin/bash -c "echo  $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C"

[module/gpu-power]
type = custom/script
exec = /bin/bash -c "echo 󰠠 $(printf "%.0f" $(nvidia-smi --query-gpu=power.draw --format=csv,noheader,nounits))W"

[module/filesystem]
type = internal/fs
mount-0 = /home/eren/ssd
fixed-values = true
label-mounted = 󰨣 %percentage_free%%

[settings]
screenchange-reload = true
